let playerVSai;
let timeTurn;
let timeOut;
let rollOne;
let active;
let SDcheck = false;
let showTurn = true;
let aiRolling = true;
let playerSw = 1;
let off = true;
let SC1 = true;
let SC2 = true;
let playerResult = 0;
let playerGoal1 = 0;
let playerGoal2 = 0;
let goal = 100;
let goalThreshold = 10;
let dontRoll1 = 6;
let stages = 1;
let coin = 30;
let state = 1;
let newState = 1;
let newState2 = 1;
let time = 400;
let level = "Easy";
let gA = [10, 20, 30, 40, 100, 70, 350];
let count = [0,0,0,0];
let recordAi = [];
let recordHum = [];